#!/usr/bin/env bash
# addon/deploy_privacy.sh
#
# PURPOSE
#   Publish privacy.html and tos.html to GitHub Pages (docs/ folder on the
#   default branch). Enables Pages via the GitHub API if not yet configured.
#   After a successful push, writes the live public URLs back into
#   addon/listing/listing.json so that launch-checks.sh and gcp-for-addon.sh
#   can reference them.
#
# USAGE
#   bash addon/deploy_privacy.sh
#
# REQUIRES
#   gh    GitHub CLI, authenticated with 'repo' scope.
#         Install:  https://cli.github.com
#         Auth:     gh auth login
#   git   Standard git
#
# SOURCE FILES
#   addon/listing/privacy.html   Generated by 03-generate-listing-assets.md
#   addon/listing/tos.html       Generated by 03-generate-listing-assets.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

LISTING_DIR="$SCRIPT_DIR/listing"
PRIVACY_SRC="$LISTING_DIR/privacy.html"
TOS_SRC="$LISTING_DIR/tos.html"
DOCS_DIR="$PROJECT_ROOT/docs"
LISTING_JSON="$LISTING_DIR/listing.json"

# ── Dependency checks ─────────────────────────────────────────────────────────
for cmd in gh git jq; do
  command -v "$cmd" >/dev/null || {
    echo "ERROR: '$cmd' is required."
    [[ "$cmd" == "gh" ]]  && echo "  Install: https://cli.github.com  |  Auth: gh auth login"
    [[ "$cmd" == "jq" ]]  && echo "  Install: brew install jq"
    exit 1
  }
done

gh auth status >/dev/null 2>&1 || {
  echo "ERROR: GitHub CLI not authenticated."
  echo "  Run: gh auth login"
  exit 1
}

# ── Verify source files exist ─────────────────────────────────────────────────
MISSING=()
[[ -f "$PRIVACY_SRC" ]] || MISSING+=("addon/listing/privacy.html")
[[ -f "$TOS_SRC"     ]] || MISSING+=("addon/listing/tos.html")

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "ERROR: required source files are missing:"
  for f in "${MISSING[@]}"; do echo "  $f"; done
  echo ""
  echo "  Generate them by running the prompt at:"
  echo "  addon/prompts/03-generate-listing-assets.md"
  exit 1
fi

# ── Repo and branch info ──────────────────────────────────────────────────────
REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
OWNER="$(echo "$REPO" | cut -d/ -f1)"
REPO_NAME="$(echo "$REPO" | cut -d/ -f2)"
DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)"

echo "Repository:     $REPO"
echo "Default branch: $DEFAULT_BRANCH"
echo ""

# ── Copy files into docs/ ─────────────────────────────────────────────────────
mkdir -p "$DOCS_DIR"
cp "$PRIVACY_SRC" "$DOCS_DIR/privacy.html"
cp "$TOS_SRC"     "$DOCS_DIR/tos.html"

# Create a minimal index if this is the first time docs/ is being set up
if [[ ! -f "$DOCS_DIR/index.html" ]]; then
  cat > "$DOCS_DIR/index.html" <<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Legal — EditorLLM</title>
  <style>
    body { font-family: sans-serif; max-width: 600px; margin: 4rem auto; padding: 0 1rem; }
    a { color: #1a73e8; }
  </style>
</head>
<body>
  <h1>Legal</h1>
  <ul>
    <li><a href="privacy.html">Privacy Policy</a></li>
    <li><a href="tos.html">Terms of Service</a></li>
  </ul>
</body>
</html>
HTML
  echo "  Created docs/index.html"
fi

# ── Commit and push ───────────────────────────────────────────────────────────
cd "$PROJECT_ROOT"
git add docs/privacy.html docs/tos.html docs/index.html

if git diff --cached --quiet; then
  echo "docs/ is already up to date — no new commit needed."
else
  git commit -m "chore: publish privacy policy and terms of service to GitHub Pages"
  git push origin "$DEFAULT_BRANCH"
  echo "✓ Pushed docs/ to $DEFAULT_BRANCH"
fi

# ── Enable / verify GitHub Pages ──────────────────────────────────────────────
echo ""
echo "Configuring GitHub Pages (source: /docs on $DEFAULT_BRANCH) ..."

PAGES_STATUS="$(gh api "repos/$REPO/pages" --jq '.status' 2>/dev/null || echo "not_found")"

if [[ "$PAGES_STATUS" == "not_found" ]]; then
  echo "  Pages not yet enabled — creating ..."
  gh api "repos/$REPO/pages" \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -f "source[branch]=$DEFAULT_BRANCH" \
    -f "source[path]=/docs" \
    --silent
  echo "  ✓ GitHub Pages enabled."
else
  echo "  Pages already configured (status: $PAGES_STATUS) — confirming /docs source ..."
  # PUT returns 422 if the source is already correct; that is safe to ignore.
  gh api "repos/$REPO/pages" \
    -X PUT \
    -H "Accept: application/vnd.github+json" \
    -f "source[branch]=$DEFAULT_BRANCH" \
    -f "source[path]=/docs" \
    --silent 2>/dev/null || true
  echo "  ✓ Source confirmed."
fi

# ── Derive public URLs ────────────────────────────────────────────────────────
# Wait briefly for the Pages API to populate the html_url field
sleep 3
PAGES_HTML_URL="$(gh api "repos/$REPO/pages" --jq '.html_url // empty' 2>/dev/null || true)"

if [[ -z "$PAGES_HTML_URL" ]]; then
  PAGES_HTML_URL="https://${OWNER}.github.io/${REPO_NAME}"
fi

PAGES_HTML_URL="${PAGES_HTML_URL%/}"   # strip trailing slash
PRIVACY_URL="$PAGES_HTML_URL/privacy.html"
TOS_URL="$PAGES_HTML_URL/tos.html"

# ── Write URLs back into listing.json ────────────────────────────────────────
if [[ -f "$LISTING_JSON" ]]; then
  jq \
    --arg pu "$PRIVACY_URL" \
    --arg tu "$TOS_URL" \
    '.privacyUrl = $pu | .tosUrl = $tu' \
    "$LISTING_JSON" > "$LISTING_JSON.tmp"
  mv "$LISTING_JSON.tmp" "$LISTING_JSON"
  echo ""
  echo "  ✓ Updated addon/listing/listing.json with live URLs."
fi

# ── Print results ─────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  GitHub Pages URLs — copy these into the GCP OAuth Consent Screen"
echo "  and the Workspace Marketplace listing."
echo ""
echo "  Privacy Policy:   $PRIVACY_URL"
echo "  Terms of Service: $TOS_URL"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "NOTE: GitHub Pages can take 1–5 minutes to build after the first push."
echo "  Verify: curl -sI \"$PRIVACY_URL\" | head -1"
