// ============================================================
// CustomAgent.ts — BaseAgent subclass driven by a CustomAgentDefinition.
//
// Skips W1 entirely: instructions are written by the user in the designated
// instruction tab, not generated by an LLM.  Supports W2 (annotateTab) and
// W3 (handleCommentThreads) based on the definition's workflows flags.
// ============================================================

class CustomAgent extends BaseAgent {

  private def_: CustomAgentDefinition;

  constructor(def: CustomAgentDefinition, modelConfig: ModelConfig = {}) {
    super(modelConfig);
    this.def_ = def;
  }

  // ── Identity ────────────────────────────────────────────────────────────────

  get tags(): string[] { return [this.def_.tag]; }
  get contextKeys(): string[] {
    return this.def_.contextTabName ? [this.def_.contextTabName] : [];
  }

  protected getAgentId(): string { return this.def_.id; }

  // Instruction-quality scoring is not applicable to custom agents (no W1).
  protected getInstructionQualityRubric(): string { return ''; }

  // ── System prompt ────────────────────────────────────────────────────────────

  protected commentSystemPrompt_(): string {
    return this.def_.systemPrompt;
  }

  // ── W2: annotateTab ──────────────────────────────────────────────────────────

  annotateTab(tabName: string): void {
    if (!this.def_.workflows.w2) {
      throw new Error(`Agent "${this.def_.displayName}" does not have W2 (annotateTab) enabled.`);
    }

    const agentName = `CustomAgent[${this.def_.displayName}]`;
    const passage = this.getTabContent_(tabName);
    if (!passage.trim()) {
      throw new Error(`Tab "${tabName}" is empty. Nothing to annotate.`);
    }

    const instructions = this.def_.instructionTabName?.trim()
      ? this.getTabContent_(this.def_.instructionTabName)
      : '';
    const contextContent = this.def_.contextTabName
      ? this.getTabContent_(this.def_.contextTabName)
      : undefined;

    const userPrompt = this.generateTabAnnotationPrompt({ instructions, contextContent, passage });

    const geminiResult = this.callLlm_(
      this.def_.systemPrompt,
      userPrompt,
      { schema: this.annotationSchema_(), tier: Constants.MODEL.FAST }
    ) as { operations: Operation[] };

    const validOps = this.validateAndFilterOperations_(geminiResult.operations, passage, agentName);

    const update: RootUpdate = {
      workflow_type: 'content_annotation',
      target_tab:   tabName,
      operations:   validOps,
      agent_name:   `[${this.def_.displayName}]`,
    };

    CollaborationService.processUpdate(update);
  }

  // ── W2 prompt builder ────────────────────────────────────────────────────────

  generateTabAnnotationPrompt(opts: {
    instructions: string;
    contextContent?: string;
    passage: string;
  }): string {
    const sections: Record<string, string | undefined | null> = {};
    if (opts.contextContent?.trim()) {
      sections[`${this.def_.contextTabName ?? 'Context'}`] = opts.contextContent;
    }
    sections['Agent Instructions'] = opts.instructions ||
      '(No instructions found on the designated instruction tab — please add content there.)';
    sections[Constants.W2_PASSAGE_SECTION_TITLE] = opts.passage;

    return buildStandardPrompt(
      sections,
      'Identify passages in the text that need attention based on the instructions above.\n' +
      'For each passage, provide the exact match_text (3–5 unique words from the passage) and a concise reason.'
    );
  }

  // ── W3 hooks ─────────────────────────────────────────────────────────────────

  protected commentChunkSize_(): number { return 10; }
  protected commentModelTier_(): ModelTier { return Constants.MODEL.FAST; }

  protected buildCommentPrompt_(chunk: CommentThread[], passageContext: string): string {
    return this.generateCommentResponsesPrompt({ passageContext, threads: chunk });
  }

  generateCommentResponsesPrompt(opts: {
    passageContext: string;
    threads: CommentThread[];
  }): string {
    const sections: Record<string, string | undefined | null> = {};

    if (this.def_.contextTabName) {
      sections[this.def_.contextTabName] = this.getTabContent_(this.def_.contextTabName);
    }

    const instructions = this.def_.instructionTabName?.trim()
      ? this.getTabContent_(this.def_.instructionTabName)
      : '';
    sections['Agent Instructions'] = instructions ||
      '(No instructions found — respond helpfully based on the context.)';

    if (opts.passageContext) {
      sections['Passage Context'] = opts.passageContext;
    }
    sections['Threads'] = this.formatThreadsForBatch_(opts.threads);

    return buildStandardPrompt(
      sections,
      `Respond to each comment thread addressed to ${this.def_.tag}.\n` +
      'Provide a concise, helpful reply for each thread based on the instructions above.'
    );
  }
}
